version: '3.8' # Compose 파일 형식의 버전

services:
  goldblin-local-db:
    image: mariadb:latest # 도커 이미지
    environment:
      MARIADB_DATABASE: ${DATABASE}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${DATABASE_PORT}:3306"
