# 1. 워크플로의 이름 지정
name: CI

# 2. 워크플로가 시작될 조건(트리거) 지정
on:
  pull_request:
    branches:
      - main

# 워크플로우가 저장소에 갖는 권한 설정
permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest # 3. 실행 환경 지정

    strategy:
      matrix:
        module: [ goldblin-order, goldblin-auth ] # 4. 각 모듈을 병렬로 빌드할 수 있도록 설정

    # 5. 실행 스텝 지정
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Gradle 의존성 캐시
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: 빌드 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 빌드
        run: ./gradlew :${{ matrix.module }}:build --parallel
